name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - uses: actions/cache@v1
          with:
              path: ~/.cache/pip
              key: ${{ hashFiles('test.py') }}
        - name: Install dependencies
          run: |
              pip install synonyms
              pip install python-levenshtein
        - name: Test
          run: |
              python test.py common.txt refuse.txt
